import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BadgeDollarSign, RefreshCw, Save, ShieldCheck } from 'lucide-react'
import { api, asPage, formatDate, formatMoney } from '../lib/api'
import { Button, DataTable, EmptyState, ErrorState, Form, Panel, Skeleton, StatusBadge, SubmitButton, useToast } from '../components/ui'

type Supplier = { id: string; display_name: string; legal_name: string; status: string; payout_currency: string }
type Policy = { supplier_id: string; enabled: boolean; settlement_cycle: string; minimum_payout: string; commission_bps: number; risk_reserve_bps: number; reserve_hold_days: number; payout_adapter: string; payout_region: string; tax_verification_required: boolean; invoice_required: boolean; next_settlement_at?: string }
type Batch = { id: string; batch_number: string; supplier_id: string; supplier_name: string; provider_id: string; provider_name: string; period_start: string; period_end: string; currency: string; gross_usage_amount: string; commission_amount: string; reserve_held_amount: string; adjustment_amount: string; payout_amount: string; status: string; tax_status: string; invoice_status: string; retry_count: number; max_attempts: number; last_failure_code?: string; created_at: string }
type Appeal = { id: string; appeal_number: string; supplier_id: string; appeal_type: string; status: string; reason: string; created_at: string }
type Bill = { id: string; bill_reference: string; supplier_id: string; provider_id: string; period_start: string; period_end: string; total_amount: string; currency: string; status: string; declared_at: string }
type Accrual = { id: string; supplier_id: string; request_id: string; gross_amount: string; commission_amount: string; reserve_amount: string; initial_payable_amount: string; currency: string; statement_matched: boolean; open_appeal: boolean; usage_settled_at: string }

const defaultPolicy: Policy = { supplier_id: '', enabled: false, settlement_cycle: 'MONTHLY', minimum_payout: '100.000000000000', commission_bps: 0, risk_reserve_bps: 0, reserve_hold_days: 30, payout_adapter: 'disabled', payout_region: '', tax_verification_required: true, invoice_required: true }

export function SupplierSettlementsPage() {
  const client = useQueryClient()
  const toast = useToast()
  const suppliers = useQuery({ queryKey: ['settlement-suppliers'], queryFn: () => api<unknown>('/suppliers', { query: { limit: 100 } }).then(asPage<Supplier>) })
  const batches = useQuery({ queryKey: ['supplier-settlements'], queryFn: () => api<unknown>('/supplier-settlements', { query: { limit: 100 } }).then(asPage<Batch>), refetchInterval: 15_000 })
  const appeals = useQuery({ queryKey: ['supplier-appeals'], queryFn: () => api<unknown>('/supplier-appeals', { query: { limit: 100 } }).then(asPage<Appeal>) })
  const bills = useQuery({ queryKey: ['supplier-bills'], queryFn: () => api<unknown>('/supplier-bills', { query: { limit: 100 } }).then(asPage<Bill>) })
  const payables = useQuery({ queryKey: ['supplier-payables'], queryFn: () => api<unknown>('/supplier-payables', { query: { limit: 100 } }).then(asPage<Accrual>) })
  const [supplierID, setSupplierID] = useState('')
  const selectedSupplier = useMemo(() => suppliers.data?.items.find((item) => item.id === supplierID) || suppliers.data?.items[0], [supplierID, suppliers.data?.items])
  const policyQuery = useQuery({ queryKey: ['supplier-settlement-policy', selectedSupplier?.id], queryFn: () => api<Policy>(`/supplier-settlement-policies/${selectedSupplier?.id}`), enabled: Boolean(selectedSupplier?.id) })
  const [policy, setPolicy] = useState<Policy>(defaultPolicy)
  const [statementByBatch, setStatementByBatch] = useState<Record<string, string>>({})
  const [reasonByBatch, setReasonByBatch] = useState<Record<string, string>>({})
  const [refund, setRefund] = useState({ accrual_id: '', amount: '', reference: '' })
  useEffect(() => { if (selectedSupplier) setSupplierID(selectedSupplier.id) }, [selectedSupplier])
  useEffect(() => { if (policyQuery.data) setPolicy(policyQuery.data) }, [policyQuery.data])
  const refresh = () => { void client.invalidateQueries({ queryKey: ['supplier-settlements'] }); void client.invalidateQueries({ queryKey: ['supplier-appeals'] }); void client.invalidateQueries({ queryKey: ['supplier-bills'] }); void client.invalidateQueries({ queryKey: ['supplier-payables'] }); void client.invalidateQueries({ queryKey: ['supplier-settlement-policy'] }) }
  const save = useMutation({ mutationFn: () => api(`/supplier-settlement-policies/${selectedSupplier?.id}`, { method: 'PUT', body: JSON.stringify(policy) }), onSuccess: () => { toast('Settlement policy saved'); refresh() } })
  const approve = useMutation({ mutationFn: (batch: Batch) => api(`/supplier-settlements/${batch.id}/approve`, { method: 'POST', body: JSON.stringify({ provider_statement_id: statementByBatch[batch.id] || '', reason: reasonByBatch[batch.id] || '' }) }), onSuccess: () => { toast('Settlement approved for payout'); refresh() } })
  const compliance = useMutation({ mutationFn: (batch: Batch) => api(`/supplier-settlements/${batch.id}/compliance`, { method: 'PATCH', body: JSON.stringify({ tax_status: 'VERIFIED', invoice_status: 'APPROVED', reason: reasonByBatch[batch.id] || 'Verified by finance operator' }) }), onSuccess: () => { toast('Tax and invoice status verified'); refresh() } })
  const retry = useMutation({ mutationFn: (batch: Batch) => api(`/supplier-settlements/${batch.id}/retry`, { method: 'POST', body: JSON.stringify({ reason: reasonByBatch[batch.id] || 'Finance-approved payout retry' }) }), onSuccess: () => { toast('Payout retry approved'); refresh() } })
  const resolveAppeal = useMutation({ mutationFn: ({ appeal, decision }: { appeal: Appeal; decision: string }) => api(`/supplier-appeals/${appeal.id}/resolve`, { method: 'POST', body: JSON.stringify({ decision, reason: `Finance review: ${decision.toLowerCase()}` }) }), onSuccess: () => { toast('Appeal resolved'); refresh() } })
  const reconcileBill = useMutation({ mutationFn: (bill: Bill) => api(`/supplier-bills/${bill.id}/reconcile`, { method: 'POST' }), onSuccess: () => { toast('Supplier declaration reconciled'); refresh() } })
  const allocateRefund = useMutation({ mutationFn: () => api(`/supplier-payables/${refund.accrual_id}/refund-share`, { method: 'POST', body: JSON.stringify({ amount: refund.amount, reference: refund.reference, idempotency_key: `refund-share-${crypto.randomUUID()}` }) }), onSuccess: () => { toast('Supplier refund share allocated'); setRefund({ accrual_id: '', amount: '', reference: '' }); refresh() } })

  return <div className="page-stack">
    <div className="page-header"><div><div className="eyebrow-row"><BadgeDollarSign size={14} />SUPPLIER PAYABLE CONTROL</div><h1>Supplier settlements</h1><p>Payouts are built only from platform-settled usage. Supplier bills remain declaration and reconciliation evidence.</p></div><Button onClick={refresh}><RefreshCw size={14} />Refresh</Button></div>
    <Panel title="Settlement policy" description="Existing suppliers are disabled by default. Enable only after KYB, contract, payout destination, adapter contract, and region review.">
      {suppliers.isLoading || policyQuery.isLoading ? <Skeleton rows={5} /> : suppliers.isError || policyQuery.isError ? <ErrorState error={suppliers.error || policyQuery.error} /> : !selectedSupplier ? <EmptyState title="No suppliers" /> : <Form className="form-grid panel-pad" onSubmit={() => save.mutateAsync()}>
        <label className="full-span"><span>Supplier</span><select value={selectedSupplier.id} onChange={(event) => setSupplierID(event.target.value)}>{suppliers.data?.items.map((item) => <option key={item.id} value={item.id}>{item.display_name || item.legal_name} · {item.status}</option>)}</select></label>
        <label><span>Cycle</span><select value={policy.settlement_cycle} onChange={(event) => setPolicy({ ...policy, settlement_cycle: event.target.value })}><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option></select></label>
        <Field label="Minimum payout" value={policy.minimum_payout} onChange={(value) => setPolicy({ ...policy, minimum_payout: value })} />
        <NumberField label="Commission bps" value={policy.commission_bps} onChange={(value) => setPolicy({ ...policy, commission_bps: value })} />
        <NumberField label="Risk reserve bps" value={policy.risk_reserve_bps} onChange={(value) => setPolicy({ ...policy, risk_reserve_bps: value })} />
        <NumberField label="Reserve hold days" value={policy.reserve_hold_days} onChange={(value) => setPolicy({ ...policy, reserve_hold_days: value })} />
        <label><span>Payout adapter</span><select value={policy.payout_adapter} onChange={(event) => setPolicy({ ...policy, payout_adapter: event.target.value })}><option value="disabled">disabled</option><option value="sandbox">sandbox (test only)</option></select></label>
        <label><span>Payout region</span><input maxLength={2} value={policy.payout_region} onChange={(event) => setPolicy({ ...policy, payout_region: event.target.value.toUpperCase() })} /></label>
        <label><span>Tax verification required</span><input type="checkbox" checked={policy.tax_verification_required} onChange={(event) => setPolicy({ ...policy, tax_verification_required: event.target.checked })} /></label>
        <label><span>Invoice required</span><input type="checkbox" checked={policy.invoice_required} onChange={(event) => setPolicy({ ...policy, invoice_required: event.target.checked })} /></label>
        <label><span>Enabled</span><input type="checkbox" checked={policy.enabled} onChange={(event) => setPolicy({ ...policy, enabled: event.target.checked })} /></label>
        <SubmitButton pending={save.isPending}><Save size={14} />Save policy</SubmitButton>
      </Form>}
    </Panel>
    <Panel title="Platform payable accruals" description="These rows come from terminal platform funding and immutable usage snapshots, never supplier declarations.">{payables.isLoading ? <Skeleton rows={4} /> : !payables.data?.items.length ? <EmptyState title="No payable accruals" /> : <DataTable rows={payables.data.items} rowKey={(row) => row.id} columns={[
      { key: 'usage', label: 'Usage', render: (row) => <div className="primary-cell"><code>{row.id}</code><small>{row.request_id} · {formatDate(row.usage_settled_at)}</small></div> }, { key: 'amounts', label: 'Gross / payable', render: (row) => <div className="primary-cell"><strong>{formatMoney(row.gross_amount, row.currency)}</strong><small>{formatMoney(row.initial_payable_amount, row.currency)} after commission/reserve</small></div> }, { key: 'evidence', label: 'Evidence', render: (row) => <div className="primary-cell"><StatusBadge value={row.statement_matched ? 'MATCHED' : 'UNMATCHED'} />{row.open_appeal && <StatusBadge value="DISPUTED" />}</div> }, { key: 'action', label: '', render: (row) => <Button size="sm" onClick={() => setRefund({ ...refund, accrual_id: row.id })}>Allocate refund</Button> },
    ]} />}</Panel>
    <Panel title="Refund sharing" description="Allocate only a reviewed customer refund to its original platform accrual. The append-only debit either reduces an unpaid batch or carries forward after payout."><Form className="form-grid panel-pad" onSubmit={() => allocateRefund.mutateAsync()}><Field label="Payable accrual UUID" value={refund.accrual_id} onChange={(value) => setRefund({ ...refund, accrual_id: value })} /><Field label="Supplier share exact amount" value={refund.amount} onChange={(value) => setRefund({ ...refund, amount: value })} /><label className="full-span"><span>Audited refund reference</span><input required value={refund.reference} onChange={(event) => setRefund({ ...refund, reference: event.target.value })} /></label><SubmitButton pending={allocateRefund.isPending}>Allocate refund share</SubmitButton></Form></Panel>
    <Panel title="Supplier bill declarations" description="Declarations never create payable. Reconciliation compares each line with platform accruals and exposes discrepancies to finance.">{bills.isLoading ? <Skeleton rows={4} /> : !bills.data?.items.length ? <EmptyState title="No supplier bills" /> : <DataTable rows={bills.data.items} rowKey={(row) => row.id} columns={[
      { key: 'bill', label: 'Bill', render: (row) => <div className="primary-cell"><strong>{row.bill_reference}</strong><small>{row.period_start} – {row.period_end}</small></div> }, { key: 'amount', label: 'Declared amount', render: (row) => formatMoney(row.total_amount, row.currency) }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, { key: 'declared', label: 'Declared', render: (row) => formatDate(row.declared_at) }, { key: 'action', label: '', render: (row) => <Button size="sm" onClick={() => reconcileBill.mutate(row)}>Reconcile</Button> },
    ]} />}</Panel>
    <Panel title="Approval and payout queue" description="Approval re-locks usage and requires an administrator-imported Provider statement line match, verified tax/invoice state, no open appeal, and four-eyes review.">
      {batches.isLoading ? <Skeleton rows={6} /> : batches.isError ? <ErrorState error={batches.error} /> : !batches.data?.items.length ? <EmptyState title="No settlement batches" /> : <DataTable rows={batches.data.items} rowKey={(row) => row.id} columns={[
        { key: 'batch', label: 'Batch', render: (row) => <div className="primary-cell"><strong>{row.batch_number}</strong><small>{row.supplier_name} · {row.provider_name}</small><small>{row.period_start} – {row.period_end}</small></div> },
        { key: 'amount', label: 'Payout', render: (row) => <div className="primary-cell"><strong>{formatMoney(row.payout_amount, row.currency)}</strong><small>Gross {formatMoney(row.gross_usage_amount, row.currency)}</small><small>Commission {formatMoney(row.commission_amount, row.currency)} · reserve {formatMoney(row.reserve_held_amount, row.currency)}</small></div> },
        { key: 'state', label: 'State', render: (row) => <div className="primary-cell"><StatusBadge value={row.status} /><small>Tax {row.tax_status} · invoice {row.invoice_status}</small><small>{row.retry_count}/{row.max_attempts} attempts {row.last_failure_code || ''}</small></div> },
        { key: 'evidence', label: 'Approval evidence', render: (row) => <div className="primary-cell"><input placeholder="Provider statement UUID" value={statementByBatch[row.id] || ''} onChange={(event) => setStatementByBatch({ ...statementByBatch, [row.id]: event.target.value })} /><input placeholder="Audited reason" value={reasonByBatch[row.id] || ''} onChange={(event) => setReasonByBatch({ ...reasonByBatch, [row.id]: event.target.value })} /></div> },
        { key: 'actions', label: '', render: (row) => <div className="header-actions"><Button size="sm" disabled={!reasonByBatch[row.id]} onClick={() => compliance.mutate(row)}><ShieldCheck size={13} />Verify tax/invoice</Button>{row.status === 'FAILED' ? <Button size="sm" disabled={!reasonByBatch[row.id]} onClick={() => retry.mutate(row)}>Retry</Button> : <Button size="sm" disabled={!reasonByBatch[row.id]} onClick={() => approve.mutate(row)}>Approve</Button>}</div> },
      ]} />}
    </Panel>
    <Panel title="Supplier appeals" description="Open usage or settlement appeals block payout. Upheld settlement appeals cancel the unpaid batch; rejected appeals return it to approval.">{appeals.isLoading ? <Skeleton rows={4} /> : !appeals.data?.items.length ? <EmptyState title="No supplier appeals" /> : <DataTable rows={appeals.data.items} rowKey={(row) => row.id} columns={[
      { key: 'appeal', label: 'Appeal', render: (row) => <div className="primary-cell"><strong>{row.appeal_number}</strong><small>{row.appeal_type} · {formatDate(row.created_at)}</small></div> }, { key: 'reason', label: 'Reason', render: (row) => row.reason }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, { key: 'action', label: '', render: (row) => row.status === 'OPEN' || row.status === 'UNDER_REVIEW' ? <div className="header-actions"><Button size="sm" onClick={() => resolveAppeal.mutate({ appeal: row, decision: 'REJECTED' })}>Reject</Button><Button size="sm" variant="danger" onClick={() => resolveAppeal.mutate({ appeal: row, decision: 'UPHELD' })}>Uphold</Button></div> : null },
    ]} />}</Panel>
  </div>
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span>{label}</span><input required inputMode="decimal" value={value} onChange={(event) => onChange(event.target.value)} /></label> }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label><span>{label}</span><input required type="number" min={0} max={10000} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label> }
