version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, ci]
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, go]
  - package-ecosystem: npm
    directory: /apps/admin-web
    schedule:
      interval: weekly
    labels: [dependencies, frontend]
  - package-ecosystem: npm
    directory: /apps/console-web
    schedule:
      interval: weekly
    labels: [dependencies, frontend]
  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
    labels: [dependencies, docker]
