import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BadgeDollarSign, FileUp, Scale } from 'lucide-react'
import { api, asPage, formatDate, formatMoney } from '../lib/api'
import { DataTable, EmptyState, ErrorState, Form, Panel, Skeleton, StatusBadge, SubmitButton, useToast } from '../components/ui'

type Supplier = { id: string; display_name: string; status: string }
type Summary = { supplier_id: string; currency: string; accrued: string; reserve_held: string; refund_share: string; paid: string; available: string; open_appeals: number; unmatched_accruals: number }
type Batch = { id: string; batch_number: string; provider_name: string; period_start: string; period_end: string; payout_amount: string; currency: string; status: string; tax_status: string; invoice_status: string; created_at: string }
type Bill = { id: string; bill_reference: string; provider_id: string; period_start: string; period_end: string; total_amount: string; currency: string; status: string; declared_at: string }
type Appeal = { id: string; appeal_number: string; appeal_type: string; status: string; reason: string; created_at: string }

function unwrapSupplier(value: unknown): Supplier | null {
  if (!value || typeof value !== 'object') return null
  const record = value as { data?: unknown }
  if (Object.prototype.hasOwnProperty.call(record, 'data')) return record.data && typeof record.data === 'object' ? record.data as Supplier : null
  return value as Supplier
}

export function SupplierSettlementsPage() {
  const client = useQueryClient(); const toast = useToast()
  const supplierQuery = useQuery({ queryKey: ['supplier-self'], queryFn: () => api<unknown>('/suppliers').then(unwrapSupplier) })
  const supplier = supplierQuery.data
  const summary = useQuery({ queryKey: ['supplier-payable-summary', supplier?.id], queryFn: () => api<unknown>(`/suppliers/${supplier?.id}/payables/summary`).then(asPage<Summary>), enabled: Boolean(supplier?.id), refetchInterval: 20_000 })
  const batches = useQuery({ queryKey: ['supplier-settlements-self', supplier?.id], queryFn: () => api<unknown>(`/suppliers/${supplier?.id}/settlements`, { query: { limit: 100 } }).then(asPage<Batch>), enabled: Boolean(supplier?.id) })
  const bills = useQuery({ queryKey: ['supplier-bills-self', supplier?.id], queryFn: () => api<unknown>(`/suppliers/${supplier?.id}/bills`, { query: { limit: 100 } }).then(asPage<Bill>), enabled: Boolean(supplier?.id) })
  const appeals = useQuery({ queryKey: ['supplier-appeals-self', supplier?.id], queryFn: () => api<unknown>(`/suppliers/${supplier?.id}/appeals`, { query: { limit: 100 } }).then(asPage<Appeal>), enabled: Boolean(supplier?.id) })
  const [bill, setBill] = useState({ provider_id: '', bill_reference: '', period_start: '', period_end: '', currency: 'USD', total_amount: '', source_sha256: '', external_line_id: '', request_id: '', usage_date: '', line_amount: '' })
  const [appeal, setAppeal] = useState({ appeal_type: 'USAGE', accrual_id: '', settlement_batch_id: '', reason: '' })
  const refresh = () => { void client.invalidateQueries({ queryKey: ['supplier-payable-summary'] }); void client.invalidateQueries({ queryKey: ['supplier-settlements-self'] }); void client.invalidateQueries({ queryKey: ['supplier-bills-self'] }); void client.invalidateQueries({ queryKey: ['supplier-appeals-self'] }) }
  const importBill = useMutation({ mutationFn: () => api(`/suppliers/${supplier?.id}/bills`, { method: 'POST', body: JSON.stringify({ provider_id: bill.provider_id, bill_reference: bill.bill_reference, period_start: bill.period_start, period_end: bill.period_end, currency: bill.currency, total_amount: bill.total_amount, source_sha256: bill.source_sha256, lines: [{ external_line_id: bill.external_line_id, request_id: bill.request_id, usage_date: `${bill.usage_date}T00:00:00Z`, amount: bill.line_amount, currency: bill.currency, metadata: {} }] }) }), onSuccess: () => { toast('Supplier bill declared for reconciliation'); refresh() } })
  const submitAppeal = useMutation({ mutationFn: () => api(`/suppliers/${supplier?.id}/appeals`, { method: 'POST', headers: { 'Idempotency-Key': `supplier-appeal-${crypto.randomUUID()}` }, body: JSON.stringify({ ...appeal, accrual_id: appeal.appeal_type === 'USAGE' ? appeal.accrual_id : undefined, settlement_batch_id: appeal.appeal_type === 'SETTLEMENT' ? appeal.settlement_batch_id : undefined, evidence: {} }) }), onSuccess: () => { toast('Appeal submitted; related payout is blocked'); setAppeal({ appeal_type: 'USAGE', accrual_id: '', settlement_batch_id: '', reason: '' }); refresh() } })
  const totals = useMemo(() => summary.data?.items || [], [summary.data?.items])

  if (supplierQuery.isLoading) return <Panel><Skeleton rows={6} /></Panel>
  if (supplierQuery.isError) return <ErrorState error={supplierQuery.error} />
  if (!supplier) return <EmptyState title="Supplier application required" description="Create and obtain approval for a supplier application before viewing payables." />
  return <div className="page-stack">
    <div className="page-header"><div><div className="eyebrow-row"><BadgeDollarSign size={14} />PLATFORM-MEASURED PAYABLES</div><h1>Supplier settlements</h1><p>Only platform-settled usage can become payable. Your uploaded bill is used for reconciliation and never creates a payout by itself.</p></div><StatusBadge value={supplier.status} /></div>
    <div className="metric-grid">{totals.map((row) => <Panel key={row.currency} title={`${row.currency} payable`}><div className="panel-pad"><strong className="billing-total">{formatMoney(row.available, row.currency)}</strong><p>Accrued {formatMoney(row.accrued, row.currency)} · reserve {formatMoney(row.reserve_held, row.currency)} · paid {formatMoney(row.paid, row.currency)}</p><p>{row.unmatched_accruals} unmatched usage · {row.open_appeals} open appeals</p></div></Panel>)}</div>
    <Panel title="Settlement history" description="Tax, invoice, approval, retry, and payout states are shown independently.">{batches.isLoading ? <Skeleton rows={5} /> : !batches.data?.items.length ? <EmptyState title="No settlements yet" /> : <DataTable rows={batches.data.items} rowKey={(row) => row.id} columns={[{ key: 'batch', label: 'Batch', render: (row) => <div className="primary-cell"><strong>{row.batch_number}</strong><small>{row.provider_name} · {row.period_start} – {row.period_end}</small></div> }, { key: 'amount', label: 'Payout', render: (row) => formatMoney(row.payout_amount, row.currency) }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, { key: 'compliance', label: 'Tax / invoice', render: (row) => `${row.tax_status} / ${row.invoice_status}` }, { key: 'created', label: 'Created', render: (row) => formatDate(row.created_at) }]} />}</Panel>
    <Panel title="Declare supplier bill" description="The source hash and exact-decimal lines are immutable. Declared data does not rank Providers, create usage, or authorize payout."><Form className="form-grid panel-pad" onSubmit={() => importBill.mutateAsync()}>
      <Field label="Provider UUID" value={bill.provider_id} onChange={(value) => setBill({ ...bill, provider_id: value })} /><Field label="Bill reference" value={bill.bill_reference} onChange={(value) => setBill({ ...bill, bill_reference: value })} /><DateField label="Period start" value={bill.period_start} onChange={(value) => setBill({ ...bill, period_start: value })} /><DateField label="Period end" value={bill.period_end} onChange={(value) => setBill({ ...bill, period_end: value })} /><Field label="Currency" value={bill.currency} onChange={(value) => setBill({ ...bill, currency: value.toUpperCase() })} /><Field label="Total exact amount" value={bill.total_amount} onChange={(value) => setBill({ ...bill, total_amount: value })} /><label className="full-span"><span>Source SHA-256</span><input required minLength={64} maxLength={64} value={bill.source_sha256} onChange={(event) => setBill({ ...bill, source_sha256: event.target.value.toLowerCase() })} /></label><Field label="External line ID" value={bill.external_line_id} onChange={(value) => setBill({ ...bill, external_line_id: value })} /><Field label="Platform request ID" value={bill.request_id} onChange={(value) => setBill({ ...bill, request_id: value })} /><DateField label="Usage date" value={bill.usage_date} onChange={(value) => setBill({ ...bill, usage_date: value })} /><Field label="Line exact amount" value={bill.line_amount} onChange={(value) => setBill({ ...bill, line_amount: value })} /><SubmitButton pending={importBill.isPending}><FileUp size={14} />Declare bill</SubmitButton>
    </Form></Panel>
    <Panel title="Bills" description="RECONCILED means every declared line matched platform-measured usage; DISCREPANT means finance review is required.">{!bills.data?.items.length ? <EmptyState title="No supplier bills" /> : <DataTable rows={bills.data.items} rowKey={(row) => row.id} columns={[{ key: 'bill', label: 'Bill', render: (row) => <div className="primary-cell"><strong>{row.bill_reference}</strong><small>{row.period_start} – {row.period_end}</small></div> }, { key: 'amount', label: 'Amount', render: (row) => formatMoney(row.total_amount, row.currency) }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, { key: 'declared', label: 'Declared', render: (row) => formatDate(row.declared_at) }]} />}</Panel>
    <Panel title="Dispute usage or settlement" description="An open appeal immediately blocks the related unpaid payout."><Form className="form-grid panel-pad" onSubmit={() => submitAppeal.mutateAsync()}><label><span>Appeal type</span><select value={appeal.appeal_type} onChange={(event) => setAppeal({ ...appeal, appeal_type: event.target.value })}><option>USAGE</option><option>SETTLEMENT</option></select></label><Field label={appeal.appeal_type === 'USAGE' ? 'Payable accrual UUID' : 'Settlement batch UUID'} value={appeal.appeal_type === 'USAGE' ? appeal.accrual_id : appeal.settlement_batch_id} onChange={(value) => setAppeal(appeal.appeal_type === 'USAGE' ? { ...appeal, accrual_id: value } : { ...appeal, settlement_batch_id: value })} /><label className="full-span"><span>Reason</span><textarea required maxLength={10000} value={appeal.reason} onChange={(event) => setAppeal({ ...appeal, reason: event.target.value })} /></label><SubmitButton pending={submitAppeal.isPending}><Scale size={14} />Submit appeal</SubmitButton></Form></Panel>
    <Panel title="Appeals">{!appeals.data?.items.length ? <EmptyState title="No appeals" /> : <DataTable rows={appeals.data.items} rowKey={(row) => row.id} columns={[{ key: 'appeal', label: 'Appeal', render: (row) => <div className="primary-cell"><strong>{row.appeal_number}</strong><small>{row.appeal_type} · {formatDate(row.created_at)}</small></div> }, { key: 'reason', label: 'Reason', render: (row) => row.reason }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }]} />}</Panel>
  </div>
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span>{label}</span><input required value={value} onChange={(event) => onChange(event.target.value)} /></label> }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span>{label}</span><input required type="date" value={value} onChange={(event) => onChange(event.target.value)} /></label> }
