[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet("COMMERCIAL_BETA", "MARKETPLACE_PRODUCTION")]
    [string]$Profile,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$')]
    [string]$EnvironmentId,
    [Parameter(Mandatory)][ValidatePattern('^sha256:[0-9a-f]{64}$')][string]$ServerImageDigest,
    [Parameter(Mandatory)][ValidatePattern('^sha256:[0-9a-f]{64}$')][string]$AdminImageDigest,
    [Parameter(Mandatory)][ValidatePattern('^sha256:[0-9a-f]{64}$')][string]$ConsoleImageDigest,
    [Parameter(Mandatory)][ValidatePattern('^[A-Z]{2}$')][string]$CustomerRegion,
    [Parameter(Mandatory)][ValidatePattern('^[A-Z]{2}$')][string]$DataProcessingRegion,
    [Parameter(Mandatory)][string]$SMTPDeliveryProofPath,
    [Parameter(Mandatory)][string]$Ed25519PrivateKeyPath,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._@:-]{1,127}$')][string]$Issuer,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._@:-]{1,127}$')][string]$CertificateIdentity,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._@:-]{1,127}$')][string]$CertificateIssuer,
    [Parameter(Mandatory)][string]$OutputPath,
    [ValidateRange(1, 72)][int]$ValidityHours = 24,
    [string]$DatabaseURL = $env:DATABASE_URL
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = "Stop"
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
if ($env:GITHUB_ACTIONS -cne "true" -or $env:GITHUB_REPOSITORY -cne "Yangjunjie-Lin/ModelDock" -or
    $env:GITHUB_RUN_ID -notmatch '^[1-9][0-9]{0,19}$' -or $env:GITHUB_RUN_ATTEMPT -notmatch '^[1-9][0-9]{0,9}$') {
    throw "Runtime Attestation V2 must be generated by a ModelDock GitHub Actions target-environment job."
}
if (@(git -C $repoRoot status --porcelain --untracked-files=all).Count -ne 0) {
    throw "Runtime Attestation generation requires a clean exact-commit checkout."
}
if (-not $DatabaseURL) { throw "DATABASE_URL is required." }
if (-not $env:MODELDOCK_ATTESTATION_ID_SALT -or $env:MODELDOCK_ATTESTATION_ID_SALT.Length -lt 32) {
    throw "MODELDOCK_ATTESTATION_ID_SALT must be a target-environment secret of at least 32 characters."
}

$keyPath = [System.IO.Path]::GetFullPath($Ed25519PrivateKeyPath)
if (-not (Test-Path -LiteralPath $keyPath -PathType Leaf)) { throw "Ed25519 private key file is missing." }
if ($keyPath.StartsWith($repoRoot + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "The Runtime Attestation private key must remain outside the repository."
}
$smtpPath = [System.IO.Path]::GetFullPath($SMTPDeliveryProofPath)
if (-not (Test-Path -LiteralPath $smtpPath -PathType Leaf)) { throw "SMTP delivery proof is missing." }

function Get-SHA256String([string]$Value) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
    $hash = [System.Security.Cryptography.SHA256]::HashData($bytes)
    return [Convert]::ToHexString($hash).ToLowerInvariant()
}
function Get-SHA256File([string]$Path) {
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}
function Get-MaskedID([string]$Value) {
    return Get-SHA256String ($env:MODELDOCK_ATTESTATION_ID_SALT + ":" + $Value)
}
function Get-RequiredEnvironment([string]$Name) {
    $value = [Environment]::GetEnvironmentVariable($Name)
    if ([string]::IsNullOrWhiteSpace($value)) { throw "$Name is required in the target deployment environment." }
    return $value.Trim()
}

$databaseUri = [Uri]$DatabaseURL
if ($databaseUri.Scheme -notin @("postgres", "postgresql")) { throw "DATABASE_URL must use postgres or postgresql." }
$credentials = $databaseUri.UserInfo.Split(':', 2)
if ($credentials.Count -ne 2) { throw "DATABASE_URL must contain a user and password." }
$env:PGHOST = $databaseUri.Host
$env:PGPORT = if ($databaseUri.Port -gt 0) { [string]$databaseUri.Port } else { "5432" }
$env:PGUSER = [Uri]::UnescapeDataString($credentials[0])
$env:PGPASSWORD = [Uri]::UnescapeDataString($credentials[1])
$env:PGDATABASE = $databaseUri.AbsolutePath.TrimStart('/')
if ($databaseUri.Query -match '(?:^|[?&])sslmode=([^&]+)') { $env:PGSSLMODE = [Uri]::UnescapeDataString($Matches[1]) }

function Invoke-DatabaseScalar([string]$SQL) {
    $lines = @(& psql --no-psqlrc --no-align --tuples-only --quiet --set ON_ERROR_STOP=1 --command $SQL 2>&1)
    if ($LASTEXITCODE -ne 0) { throw "Target database Attestation query failed: $([string]::Join(' ', $lines))" }
    return [string]::Join("", $lines).Trim()
}

$commit = (git -C $repoRoot rev-parse HEAD).Trim()
$tree = (git -C $repoRoot rev-parse "HEAD^{tree}").Trim()
$version = (Get-Content -LiteralPath (Join-Path $repoRoot "VERSION") -Raw).Trim()
$migration = (Get-ChildItem -LiteralPath (Join-Path $repoRoot "migrations") -File -Filter "*.sql" |
    Where-Object BaseName -Match '^[0-9]{4}_[a-z0-9_]+$' | Sort-Object BaseName | Select-Object -Last 1).BaseName
$databaseMigration = Invoke-DatabaseScalar "SELECT lpad(version::text,4,'0')||'_'||name FROM schema_migrations ORDER BY version DESC LIMIT 1"
if ($databaseMigration -cne $migration) {
    throw "Target database migration $databaseMigration does not match checkout migration $migration."
}

$providerJSON = Invoke-DatabaseScalar @"
SELECT COALESCE(json_agg(json_build_object(
  'id',candidate.id::text,
  'commercial_status',candidate.commercial_status,
  'resale_approved',candidate.resale_approved,
  'contract_valid_from',candidate.contract_start_at,
  'contract_valid_to',candidate.contract_end_at,
  'customer_region_approved',true,
  'data_processing_region_approved',true,
  'current_price_verified',candidate.current_price_verified,
  'kill_switch_enabled',candidate.kill_switch_enabled
) ORDER BY candidate.id),'[]'::json)::text
FROM commercial_runtime_provider_candidates_v2 candidate
WHERE (candidate.allowed_customer_regions ? '*' OR candidate.allowed_customer_regions ? '$CustomerRegion')
  AND (candidate.data_processing_regions ? '*' OR candidate.data_processing_regions ? '$DataProcessingRegion')
"@
$supplierJSON = Invoke-DatabaseScalar @"
SELECT COALESCE(json_agg(json_build_object(
  'id',candidate.id::text,
  'kyb_approved',candidate.kyb_approved,
  'contract_active',candidate.contract_active,
  'tax_ready',candidate.tax_ready,
  'invoice_ready',candidate.invoice_ready,
  'payout_ready',candidate.payout_ready,
  'security_review_approved',candidate.security_review_approved
) ORDER BY candidate.id),'[]'::json)::text
FROM commercial_runtime_supplier_candidates_v2 candidate
"@
$invalidDecimalRows = [int64](Invoke-DatabaseScalar "SELECT COALESCE(sum(invalid_rows),0) FROM commercial_decimal_integrity_v2()")
$providers = @($providerJSON | ConvertFrom-Json)
$suppliers = @($supplierJSON | ConvertFrom-Json)
foreach ($provider in $providers) {
    $provider | Add-Member -NotePropertyName id_hash -NotePropertyValue (Get-MaskedID ([string]$provider.id))
    $provider.PSObject.Properties.Remove("id")
}
foreach ($supplier in $suppliers) {
    $supplier | Add-Member -NotePropertyName id_hash -NotePropertyValue (Get-MaskedID ([string]$supplier.id))
    $supplier.PSObject.Properties.Remove("id")
}

$smtpProof = Get-Content -LiteralPath $smtpPath -Raw | ConvertFrom-Json
if ([string]$smtpProof.environment_id -cne $EnvironmentId -or [string]$smtpProof.status -cne "PASS" -or
    [string]::IsNullOrWhiteSpace([string]$smtpProof.provider_id)) {
    throw "SMTP delivery proof does not bind the target environment and a PASS delivery result."
}
$smtpTestedAt = [DateTimeOffset]::Parse([string]$smtpProof.tested_at)
if ($smtpTestedAt -gt [DateTimeOffset]::UtcNow -or $smtpTestedAt -lt [DateTimeOffset]::UtcNow.AddHours(-24)) {
    throw "SMTP delivery proof is future-dated or older than 24 hours."
}

$paymentType = (Get-RequiredEnvironment "MODELDOCK_RUNTIME_PAYMENT_ADAPTER").ToLowerInvariant()
$paymentReady = (Get-RequiredEnvironment "MODELDOCK_RUNTIME_PAYMENT_PRODUCTION_READY") -ceq "true"
if ($paymentType -in @("sandbox", "manual_transfer")) { $paymentReady = $false }
$payoutType = (Get-RequiredEnvironment "MODELDOCK_RUNTIME_PAYOUT_ADAPTER").ToLowerInvariant()
$payoutReady = (Get-RequiredEnvironment "MODELDOCK_RUNTIME_PAYOUT_PRODUCTION_READY") -ceq "true"
if ($payoutType -eq "sandbox") { $payoutReady = $false }
$configurationValues = [ordered]@{
    PAYMENT_ADAPTER=$paymentType
    PAYMENT_PRODUCTION_READY=$paymentReady
    PAYOUT_ADAPTER=$payoutType
    PAYOUT_PRODUCTION_READY=$payoutReady
    SMTP_PROVIDER=[string]$smtpProof.provider_id
}
$configurationJSON = $configurationValues | ConvertTo-Json -Compress
$databaseSummaryJSON = [ordered]@{
    providers=$providers
    suppliers=$suppliers
    invalid_decimal_rows=$invalidDecimalRows
    migration=$databaseMigration
} | ConvertTo-Json -Depth 10 -Compress
$generatedAt = [DateTimeOffset]::UtcNow
$unsigned = [ordered]@{
    schema_version="2.0.0"
    release_profile=$Profile
    repository=$env:GITHUB_REPOSITORY
    environment_id=$EnvironmentId
    commit_sha=$commit
    tree_sha=$tree
    version=$version
    migration_version=$migration
    server_image_digest=$ServerImageDigest
    admin_image_digest=$AdminImageDigest
    console_image_digest=$ConsoleImageDigest
    payment_adapter=[ordered]@{ type=$paymentType; production_ready=$paymentReady }
    payout_adapter=[ordered]@{ type=$payoutType; production_ready=$payoutReady }
    smtp=[ordered]@{
        provider_id_hash=(Get-MaskedID ([string]$smtpProof.provider_id))
        delivery_verified=$true
        delivery_proof_sha256=(Get-SHA256File $smtpPath)
    }
    commercially_approved_providers=$providers
    production_ready_suppliers=$suppliers
    database_query_summary=[ordered]@{
        commercially_approved_provider_count=$providers.Count
        production_ready_supplier_count=$suppliers.Count
        invalid_decimal_rows=$invalidDecimalRows
        summary_sha256=(Get-SHA256String $databaseSummaryJSON)
    }
    configuration_summary=[ordered]@{
        sha256=(Get-SHA256String $configurationJSON)
        redacted_keys=@($configurationValues.Keys)
    }
    generated_at=$generatedAt.ToString("o")
    expires_at=$generatedAt.AddHours($ValidityHours).ToString("o")
    workflow_run_id=[string]$env:GITHUB_RUN_ID
    workflow_run_attempt=[string]$env:GITHUB_RUN_ATTEMPT
    issuer=$Issuer
    issuer_role="Operations"
    signature_type="ed25519"
    signature=""
    certificate_identity=$CertificateIdentity
    certificate_issuer=$CertificateIssuer
}

$output = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($output)) | Out-Null
$unsignedPath = Join-Path ([System.IO.Path]::GetTempPath()) ("modeldock-runtime-" + [Guid]::NewGuid().ToString("N") + ".json")
try {
    [System.IO.File]::WriteAllText($unsignedPath, ($unsigned | ConvertTo-Json -Depth 12), (New-Object System.Text.UTF8Encoding($false)))
    & node (Join-Path $repoRoot "scripts/sign-attestation.mjs") $unsignedPath $output $keyPath
    if ($LASTEXITCODE -ne 0) { throw "Runtime Attestation signing failed." }
} finally {
    Remove-Item -LiteralPath $unsignedPath -Force -ErrorAction SilentlyContinue
}
Write-Host "Generated signed Runtime Attestation V2 for $EnvironmentId at $output; provider IDs and supplier IDs are salted hashes."
