[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$GateId,
    [Parameter(Mandatory)]
    [ValidateSet("COMMERCIAL_BETA", "MARKETPLACE_PRODUCTION")]
    [string]$Profile,
    [Parameter(Mandatory)]
    [ValidateSet("Owner", "Legal", "Finance", "Commercial", "Security", "Operations", "IndependentTester")]
    [string]$IssuerRole,
    [Parameter(Mandatory)][string]$EvidenceRoot,
    [Parameter(Mandatory)][string]$EvidencePath,
    [Parameter(Mandatory)][string]$Ed25519PrivateKeyPath,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._@:-]{1,127}$')][string]$Issuer,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._@:-]{1,127}$')][string]$CertificateIdentity,
    [Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._@:-]{1,127}$')][string]$CertificateIssuer,
    [Parameter(Mandatory)][string]$OutputPath,
    [ValidateRange(1, 8760)][int]$ValidityHours = 720
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = "Stop"
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
if ($env:GITHUB_ACTIONS -cne "true" -or $env:GITHUB_REPOSITORY -cne "Yangjunjie-Lin/ModelDock" -or
    $env:GITHUB_RUN_ID -notmatch '^[1-9][0-9]{0,19}$' -or $env:GITHUB_RUN_ATTEMPT -notmatch '^[1-9][0-9]{0,9}$') {
    throw "External Evidence Attestations must be generated by a protected ModelDock GitHub Actions workflow."
}
if (@(git -C $repoRoot status --porcelain --untracked-files=all).Count -ne 0) {
    throw "Evidence Attestation generation requires a clean exact-commit checkout."
}
$manifest = Get-Content -LiteralPath (Join-Path $repoRoot "release/commercial-gates.json") -Raw | ConvertFrom-Json
$gate = @($manifest.gates | Where-Object id -CEQ $GateId)
if ($gate.Count -ne 1 -or $Profile -notin @($gate[0].profiles) -or $IssuerRole -notin @($gate[0].required_roles)) {
    throw "Gate, profile, or issuer role is not in the mandatory Gate catalog."
}
$root = [System.IO.Path]::GetFullPath($EvidenceRoot)
$evidence = [System.IO.Path]::GetFullPath($EvidencePath)
if (-not $evidence.StartsWith($root + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase) -or
    -not (Test-Path -LiteralPath $evidence -PathType Leaf)) {
    throw "Evidence must be an existing file below the controlled Evidence Root."
}
$relative = [System.IO.Path]::GetRelativePath($root, $evidence).Replace('\', '/')
if ($relative -notmatch '^[A-Za-z0-9][A-Za-z0-9._/-]{0,255}$') { throw "Evidence reference is not an opaque safe relative path." }
$keyPath = [System.IO.Path]::GetFullPath($Ed25519PrivateKeyPath)
if (-not (Test-Path -LiteralPath $keyPath -PathType Leaf) -or
    $keyPath.StartsWith($repoRoot + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "The Ed25519 private key must exist outside the repository."
}
$commit = (git -C $repoRoot rev-parse HEAD).Trim()
$tree = (git -C $repoRoot rev-parse "HEAD^{tree}").Trim()
$version = (Get-Content -LiteralPath (Join-Path $repoRoot "VERSION") -Raw).Trim()
$migration = (Get-ChildItem -LiteralPath (Join-Path $repoRoot "migrations") -File -Filter "*.sql" |
    Where-Object BaseName -Match '^[0-9]{4}_[a-z0-9_]+$' | Sort-Object BaseName | Select-Object -Last 1).BaseName
$approvedAt = [DateTimeOffset]::UtcNow
$attestation = [ordered]@{
    schema_version="2.0.0"
    gate_id=$GateId
    release_profile=$Profile
    repository=$env:GITHUB_REPOSITORY
    reviewed_commit=$commit
    reviewed_tree=$tree
    version=$version
    migration_version=$migration
    evidence_reference=$relative
    evidence_sha256=(Get-FileHash -LiteralPath $evidence -Algorithm SHA256).Hash.ToLowerInvariant()
    issuer=$Issuer
    issuer_role=$IssuerRole
    approved_at=$approvedAt.ToString("o")
    expires_at=$approvedAt.AddHours($ValidityHours).ToString("o")
    workflow_run_id=[string]$env:GITHUB_RUN_ID
    workflow_run_attempt=[string]$env:GITHUB_RUN_ATTEMPT
    signature_type="ed25519"
    signature=""
    certificate_identity=$CertificateIdentity
    certificate_issuer=$CertificateIssuer
}
$output = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($output)) | Out-Null
$unsignedPath = Join-Path ([System.IO.Path]::GetTempPath()) ("modeldock-evidence-" + [Guid]::NewGuid().ToString("N") + ".json")
try {
    [System.IO.File]::WriteAllText($unsignedPath, ($attestation | ConvertTo-Json -Depth 8), (New-Object System.Text.UTF8Encoding($false)))
    & node (Join-Path $repoRoot "scripts/sign-attestation.mjs") $unsignedPath $output $keyPath
    if ($LASTEXITCODE -ne 0) { throw "Evidence Attestation signing failed." }
} finally {
    Remove-Item -LiteralPath $unsignedPath -Force -ErrorAction SilentlyContinue
}
Write-Host "Generated signed Evidence Attestation V2 for $GateId/$IssuerRole. No evidence body or private key was written to the repository."
