[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version 3.0
$ErrorActionPreference = "Stop"
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$manifest = Get-Content -LiteralPath (Join-Path $repoRoot "release/commercial-gates.json") -Raw | ConvertFrom-Json
$version = (Get-Content -LiteralPath (Join-Path $repoRoot "VERSION") -Raw).Trim()
$migration = (Get-ChildItem -LiteralPath (Join-Path $repoRoot "migrations") -File -Filter "*.sql" | Where-Object BaseName -Match '^\d{4}_[a-z0-9_]+$' | Sort-Object BaseName | Select-Object -Last 1).BaseName

& (Join-Path $PSHOME "pwsh") -NoProfile -File (Join-Path $repoRoot "scripts/verify-exact-money.ps1") -RepositoryRoot $repoRoot *> $null
if ($LASTEXITCODE -ne 0) { throw "Engineering exact-money status cannot be generated." }

$readmeBlock = @"
<!-- commercial-status:start -->
| Release profile | Machine decision |
| --- | --- |
| Engineering Preview | Candidate — protected CI required |
| Commercial operation | NO-GO |
| Marketplace production | NO-GO |

Protected status: [ModelDock CI](https://github.com/Yangjunjie-Lin/ModelDock/actions/workflows/ci.yml) · [Release gate](https://github.com/Yangjunjie-Lin/ModelDock/actions/workflows/release.yml)

Tracked metadata: VERSION ``$version`` · Migration ``$migration`` · Gate schema V$($manifest.schema_version). Exact Commit/Tree/Image evidence exists only in clean-worktree CI artifacts.
<!-- commercial-status:end -->
"@.Trim()

$generated = [System.Collections.Generic.List[string]]::new()
$generated.Add("# Generated commercial readiness status snapshot")
$generated.Add("")
$generated.Add("> **NOT RELEASE EVIDENCE.** Generated by scripts/update-readme-commercial-status.ps1; exact identity is generated after checkout into a CI artifact.")
$generated.Add("")
$generated.Add("- Version: $version")
$generated.Add("- Latest migration: $migration")
$generated.Add("- Manifest schema: $($manifest.schema_version)")
$generated.Add("- Engineering Preview: **CANDIDATE — protected CI required**")
$generated.Add("- Commercial Beta: **NO-GO**")
$generated.Add("- Marketplace Production: **NO-GO**")
$generated.Add("")
$generated.Add("| Gate | Profiles | Required roles | Current signed evidence |")
$generated.Add("| --- | --- | --- | --- |")
foreach ($gate in $manifest.gates) {
    $generated.Add("| $($gate.id) | $($gate.profiles -join ', ') | $($gate.required_roles -join ' + ') | **BLOCKED** — no signed Artifact Bundle supplied |")
}
$generated.Add("")
$generated.Add("Runtime and external Attestations are CI Artifact inputs, never same-commit Manifest fields. Any missing/invalid/expired signature or any NOT RUN security scan remains BLOCKED.")

$goLive = [System.Collections.Generic.List[string]]::new()
$goLive.Add("# ModelDock go-live report contract")
$goLive.Add("")
$goLive.Add("> **NOT RELEASE EVIDENCE.** Machine-generated tracked contract; do not edit. The exact-commit report is emitted to the ignored .cache directory and uploaded by CI.")
$goLive.Add("")
$goLive.Add("**Decision: NO-GO**")
$goLive.Add("**Candidate version:** ``$version``")
$goLive.Add("**Latest migration:** ``$migration``")
$goLive.Add("**Exact commit:** generated and checked against HEAD only in the CI artifact")
$goLive.Add("**Release created:** no")
$goLive.Add("")
$goLive.Add("The Decision above is output-only. `scripts/verify-commercial-readiness.ps1` never reads this file. It evaluates Schema → exact-commit test evidence → Runtime Attestation → external signed Attestations → same-digest scans/SBOM/provenance → finance/authority gates, then writes the exact report.")
$goLive.Add("")
$goLive.Add("Current external and runtime Attestations are absent, so COMMERCIAL_BETA and MARKETPLACE_PRODUCTION are machine-blocked. No Tag, Release, image promotion, or production deployment is authorized.")

function Set-OrCheck([string]$Path, [string]$Expected, [string]$Label) {
    $expectedNormalized = $Expected.TrimEnd("`r", "`n") + "`n"
    if ($Check) {
        $actual = [System.IO.File]::ReadAllText($Path).Replace("`r`n", "`n")
        if ($actual -cne $expectedNormalized.Replace("`r`n", "`n")) { throw "$Label is stale or hand-edited; run scripts/update-readme-commercial-status.ps1." }
        return
    }
    [System.IO.File]::WriteAllText($Path, $expectedNormalized, (New-Object System.Text.UTF8Encoding($false)))
}

$readmePath = Join-Path $repoRoot "README.md"
$source = [System.IO.File]::ReadAllText($readmePath)
$pattern = '(?s)<!-- commercial-status:start -->.*?<!-- commercial-status:end -->'
if ($source -notmatch $pattern) { throw "README commercial status markers are missing." }
$updatedReadme = [regex]::Replace($source, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $readmeBlock }, 1)
Set-OrCheck $readmePath $updatedReadme "README commercial status"
Set-OrCheck (Join-Path $repoRoot "docs/generated/commercial-readiness-report.md") ([string]::Join("`n", $generated)) "Generated commercial report"
Set-OrCheck (Join-Path $repoRoot "docs/go-live-checklist.md") ([string]::Join("`n", $goLive)) "Go-live report contract"
Write-Host $(if ($Check) { "PASS tracked commercial status outputs are machine-current." } else { "Updated README and tracked commercial status outputs." })
